VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "SQLiteCRecordsetADO"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Attribute VB_Description = "Constructs ADO Recordset"
'@Folder "SQLiteC For VBA.RecordsetADO"
'@ModuleDescription "Constructs ADO Recordset"
'@Exposed
'@PredeclaredId
Option Explicit
