Attribute VB_Name = "SQLiteCConst"
'@Folder "SQLiteC For VBA"
Option Explicit

Public Const SQLITE_STATIC      As Long = 0
Public Const SQLITE_TRANSIENT   As Long = -1

Public Enum SQLiteErrors
    SQLITE_OK = 0&
    SQLITE_ERROR = 1&
    SQLITE_INTERNAL = 2&
    SQLITE_PERM = 3&
    SQLITE_ABORT = 4&
    SQLITE_BUSY = 5&
    SQLITE_LOCKED = 6&
    SQLITE_NOMEM = 7&
    SQLITE_READONLY = 8&
    SQLITE_INTERRUPT = 9&
    SQLITE_IOERR = 10&
    SQLITE_CORRUPT = 11&
    SQLITE_NOTFOUND = 12&
    SQLITE_FULL = 13&
    SQLITE_CANTOPEN = 14&
    SQLITE_PROTOCOL = 15&
    SQLITE_EMPTY = 16&
    SQLITE_SCHEMA = 17&
    SQLITE_TOOBIG = 18&
    SQLITE_CONSTRAINT = 19&
    SQLITE_MISMATCH = 20&
    SQLITE_MISUSE = 21&
    SQLITE_NOLFS = 22&
    SQLITE_AUTH = 23&
    SQLITE_FORMAT = 24&
    SQLITE_RANGE = 25&
    SQLITE_NOTADB = 26&
    SQLITE_NOTICE = 27&
    SQLITE_WARNING = 28&
    SQLITE_ROW = 100&
    SQLITE_DONE = 101&
    SQLITE_ERROR_MISSING_COLLSEQ = SQLITE_ERROR + 1 * 256
    SQLITE_ERROR_RETRY = SQLITE_ERROR + 2 * 256
    SQLITE_ERROR_SNAPSHOT = SQLITE_ERROR + 3 * 256
    SQLITE_IOERR_READ = SQLITE_IOERR + 1 * 256
    SQLITE_IOERR_SHORT_READ = SQLITE_IOERR + 2 * 256
    SQLITE_IOERR_WRITE = SQLITE_IOERR + 3 * 256
    SQLITE_IOERR_FSYNC = SQLITE_IOERR + 4 * 256
    SQLITE_IOERR_DIR_FSYNC = SQLITE_IOERR + 5 * 256
    SQLITE_IOERR_TRUNCATE = SQLITE_IOERR + 6 * 256
    SQLITE_IOERR_FSTAT = SQLITE_IOERR + 7 * 256
    SQLITE_IOERR_UNLOCK = SQLITE_IOERR + 8 * 256
    SQLITE_IOERR_RDLOCK = SQLITE_IOERR + 9 * 256
    SQLITE_IOERR_DELETE = SQLITE_IOERR + 10 * 256
    SQLITE_IOERR_BLOCKED = SQLITE_IOERR + 11 * 256
    SQLITE_IOERR_NOMEM = SQLITE_IOERR + 12 * 256
    SQLITE_IOERR_ACCESS = SQLITE_IOERR + 13 * 256
    SQLITE_IOERR_CHECKRESERVEDLOCK = SQLITE_IOERR + 14 * 256
    SQLITE_IOERR_LOCK = SQLITE_IOERR + 15 * 256
    SQLITE_IOERR_CLOSE = SQLITE_IOERR + 16 * 256
    SQLITE_IOERR_DIR_CLOSE = SQLITE_IOERR + 17 * 256
    SQLITE_IOERR_SHMOPEN = SQLITE_IOERR + 18 * 256
    SQLITE_IOERR_SHMSIZE = SQLITE_IOERR + 19 * 256
    SQLITE_IOERR_SHMLOCK = SQLITE_IOERR + 20 * 256
    SQLITE_IOERR_SHMMAP = SQLITE_IOERR + 21 * 256
    SQLITE_IOERR_SEEK = SQLITE_IOERR + 22 * 256
    SQLITE_IOERR_DELETE_NOENT = SQLITE_IOERR + 23 * 256
    SQLITE_IOERR_MMAP = SQLITE_IOERR + 24 * 256
    SQLITE_IOERR_GETTEMPPATH = SQLITE_IOERR + 25 * 256
    SQLITE_IOERR_CONVPATH = SQLITE_IOERR + 26 * 256
    SQLITE_IOERR_VNODE = SQLITE_IOERR + 27 * 256
    SQLITE_IOERR_AUTH = SQLITE_IOERR + 28 * 256
    SQLITE_IOERR_BEGIN_ATOMIC = SQLITE_IOERR + 29 * 256
    SQLITE_IOERR_COMMIT_ATOMIC = SQLITE_IOERR + 30 * 256
    SQLITE_IOERR_ROLLBACK_ATOMIC = SQLITE_IOERR + 31 * 256
    SQLITE_IOERR_DATA = SQLITE_IOERR + 32 * 256
    SQLITE_IOERR_CORRUPTFS = SQLITE_IOERR + 33 * 256
    SQLITE_LOCKED_SHAREDCACHE = SQLITE_LOCKED + 1 * 256
    SQLITE_LOCKED_VTAB = SQLITE_LOCKED + 2 * 256
    SQLITE_BUSY_RECOVERY = SQLITE_BUSY + 1 * 256
    SQLITE_BUSY_SNAPSHOT = SQLITE_BUSY + 2 * 256
    SQLITE_BUSY_TIMEOUT = SQLITE_BUSY + 3 * 256
    SQLITE_CANTOPEN_NOTEMPDIR = SQLITE_CANTOPEN + 1 * 256
    SQLITE_CANTOPEN_ISDIR = SQLITE_CANTOPEN + 2 * 256
    SQLITE_CANTOPEN_FULLPATH = SQLITE_CANTOPEN + 3 * 256
    SQLITE_CANTOPEN_CONVPATH = SQLITE_CANTOPEN + 4 * 256
    SQLITE_CANTOPEN_DIRTYWAL = SQLITE_CANTOPEN + 5 * 256
    SQLITE_CANTOPEN_SYMLINK = SQLITE_CANTOPEN + 6 * 256
    SQLITE_CORRUPT_VTAB = SQLITE_CORRUPT + 1 * 256
    SQLITE_CORRUPT_SEQUENCE = SQLITE_CORRUPT + 2 * 256
    SQLITE_CORRUPT_INDEX = SQLITE_CORRUPT + 3 * 256
    SQLITE_READONLY_RECOVERY = SQLITE_READONLY + 1 * 256
    SQLITE_READONLY_CANTLOCK = SQLITE_READONLY + 2 * 256
    SQLITE_READONLY_ROLLBACK = SQLITE_READONLY + 3 * 256
    SQLITE_READONLY_DBMOVED = SQLITE_READONLY + 4 * 256
    SQLITE_READONLY_CANTINIT = SQLITE_READONLY + 5 * 256
    SQLITE_READONLY_DIRECTORY = SQLITE_READONLY + 6 * 256
    SQLITE_ABORT_ROLLBACK = SQLITE_ABORT + 2 * 256
    SQLITE_CONSTRAINT_CHECK = SQLITE_CONSTRAINT + 1 * 256
    SQLITE_CONSTRAINT_COMMITHOOK = SQLITE_CONSTRAINT + 2 * 256
    SQLITE_CONSTRAINT_FOREIGNKEY = SQLITE_CONSTRAINT + 3 * 256
    SQLITE_CONSTRAINT_FUNCTION = SQLITE_CONSTRAINT + 4 * 256
    SQLITE_CONSTRAINT_NOTNULL = SQLITE_CONSTRAINT + 5 * 256
    SQLITE_CONSTRAINT_PRIMARYKEY = SQLITE_CONSTRAINT + 6 * 256
    SQLITE_CONSTRAINT_TRIGGER = SQLITE_CONSTRAINT + 7 * 256
    SQLITE_CONSTRAINT_UNIQUE = SQLITE_CONSTRAINT + 8 * 256
    SQLITE_CONSTRAINT_VTAB = SQLITE_CONSTRAINT + 9 * 256
    SQLITE_CONSTRAINT_ROWID = SQLITE_CONSTRAINT + 10 * 256
    SQLITE_CONSTRAINT_PINNED = SQLITE_CONSTRAINT + 11 * 256
    SQLITE_NOTICE_RECOVER_WAL = SQLITE_NOTICE + 1 * 256
    SQLITE_NOTICE_RECOVER_ROLLBACK = SQLITE_NOTICE + 2 * 256
    SQLITE_WARNING_AUTOINDEX = SQLITE_WARNING + 1 * 256
    SQLITE_AUTH_USER = SQLITE_AUTH + 1 * 256
    SQLITE_OK_LOAD_PERMANENTLY = SQLITE_OK + 1 * 256
    SQLITE_OK_SYMLINK = SQLITE_OK + 2 * 256
End Enum


Public Enum SQLiteOpenFlags
    SQLITE_OPEN_READONLY = &H1&
    SQLITE_OPEN_READWRITE = &H2&
    SQLITE_OPEN_CREATE = &H4&
    SQLITE_OPEN_DELETEONCLOSE = &H8&
    SQLITE_OPEN_EXCLUSIVE = &H10&
    SQLITE_OPEN_AUTOPROXY = &H20&
    SQLITE_OPEN_URI = &H40&
    SQLITE_OPEN_MEMORY = &H80&
    SQLITE_OPEN_MAIN_DB = &H100&
    SQLITE_OPEN_TEMP_DB = &H200&
    SQLITE_OPEN_TRANSIENT_DB = &H400&
    SQLITE_OPEN_MAIN_JOURNAL = &H800&
    SQLITE_OPEN_TEMP_JOURNAL = &H1000&
    SQLITE_OPEN_SUBJOURNAL = &H2000&
    SQLITE_OPEN_SUPER_JOURNAL = &H4000&
    SQLITE_OPEN_NOMUTEX = &H8000&
    SQLITE_OPEN_FULLMUTEX = &H10000
    SQLITE_OPEN_SHAREDCACHE = &H20000
    SQLITE_OPEN_PRIVATECACHE = &H40000
    SQLITE_OPEN_WAL = &H80000
    SQLITE_OPEN_NOFOLLOW = &H1000000
End Enum


Public Enum SQLiteTypes
    SQLITE_INTEGER = 1&
    SQLITE_FLOAT = 2&
    SQLITE_TEXT = 3&
    SQLITE_BLOB = 4&
    SQLITE_NULL = 5&
End Enum

